# Site settings
name: Gayathri Pulagam
title: Gayathri Pulagam | Data Scientist
description: I am passionate about data analysis and mining 
url: https://gayathripulagam.github.io/
baseurl: ''
email: gayathri.pulagam@sjsu.edu
cover: https://gayathripulagam.github.io/img/og.png
logo: https://gayathripulagam.github.io/img/emojis/technologist.png
resume: https://gayathripulagam.github.io/resume.pdf
social:
  - title: email
    url: mailto:gayathri.pulagam@sjsu.edu
  - title: github
    url: https://github.com/gayathripulagam
  - title: linkedin
    url: https://www.linkedin.com/in/gpulagam

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
